spring.application.name=recruitment-backend
server.port=8080

# DataSource
# MySQL as default database
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/recruitment_system?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:yabetsTD0633#}
spring.datasource.driver-class-name=${DB_DRIVER:com.mysql.cj.jdbc.Driver}

# JPA

# JPA ? validate means Hibernate checks schema but does NOT create/drop tables
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=${HIBERNATE_DIALECT:org.hibernate.dialect.MySQLDialect}

# JWT
jwt.secret=insa-recruitment-super-secret-key-2025-must-be-at-least-256-bits-long
jwt.expiration=86400000
